# Generated by Django 3.2.16 on 2022-12-05 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('src', models.CharField(max_length=500)),
                ('dst', models.CharField(max_length=500)),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('uber', models.BooleanField()),
                ('group', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_req', models.CharField(max_length=500)),
                ('req_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_by', to=settings.AUTH_USER_MODEL)),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to='wesPool.ride')),
            ],
        ),
    ]
